# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  enhancd = {
    pname = "enhancd";
    version = "aec0e0c1c0b1376e87da74b8940fda5657269948";
    src = fetchgit {
      url = "https://github.com/b4b4r07/enhancd.git";
      rev = "aec0e0c1c0b1376e87da74b8940fda5657269948";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "13n2c2kj25g8aqvlkb5j4vzcz5a4a22yc8v6ary651lpqgckx7cg";
    };
    
  };
  fast-syntax-highlighting = {
    pname = "fast-syntax-highlighting";
    version = "v1.55";
    src = fetchgit {
      url = "https://github.com/zdharma/fast-syntax-highlighting";
      rev = "v1.55";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0h7f27gz586xxw7cc0wyiv3bx0x3qih2wwh05ad85bh2h834ar8d";
    };
    
  };
  fzy = {
    pname = "fzy";
    version = "519327d9990fbea50f71649e378e650f594bb39b";
    src = fetchgit {
      url = "https://github.com/aperezdc/zsh-fzy.git";
      rev = "519327d9990fbea50f71649e378e650f594bb39b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0lpnqbhdr4qiz9c8k04mf1gvlmdh97qdisrcvvwy92va2aaiz5qb";
    };
    
  };
  nix-shell = {
    pname = "nix-shell";
    version = "f8574f27e1d7772629c9509b2116d504798fe30a";
    src = fetchgit {
      url = "https://github.com/chisui/zsh-nix-shell.git";
      rev = "f8574f27e1d7772629c9509b2116d504798fe30a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0svskd09vvbzqk2ziw6iaz1md25xrva6s6dhjfb471nqb13brmjq";
    };
    
  };
}
